### ISSUE TITLE
Models not showing

### ISSUE THREAD

**Issue by Tosyk** [ShinyHobo/BG3-Modders-Multitool#120] opened 2023-08-16 07:06 UTC
Either it's Index Search or Object Explorer, I can't load any models in preview. Stuck on loading.
<img width="1179" alt="image" src="https://github.com/ShinyHobo/BG3-Modders-Multitool/assets/24209966/26b08969-38b9-4f69-8d22-82a618aa03f0">
![image](https://github.com/ShinyHobo/BG3-Modders-Multitool/assets/24209966/344aaa9d-fdfc-42f9-aaae-b12dcaf96997)

I followed this tutorial: https://www.youtube.com/watch?v=frgJdEibMNA

Can this be fixed?

**Comment by ShinyHobo** [comment] 2023-08-16 13:28
This was fixed in the latest pre-release https://github.com/ShinyHobo/BG3-Modders-Multitool/releases/tag/v0.9.1

**Closed by ShinyHobo** 2023-08-16 13:28 UTC

**Comment by ShinyHobo** [comment] 2023-08-16 16:17
If you downloaded 0.9.1 when I first made the release, it doesn't work. I uploaded a new version that had this specific fix in it. I cannot reproduce your issue in this latest version:
![image](https://github.com/ShinyHobo/BG3-Modders-Multitool/assets/6206737/07b4d889-56e2-4b95-8bea-c33c43d43ffb)

**Comment by Tosyk** [comment] 2023-08-16 16:55
okay, thanks for clarification. this makes me confused
<img width="115" alt="image" src="https://github.com/ShinyHobo/BG3-Modders-Multitool/assets/24209966/7be8148a-bd88-4846-96b8-a0c85d87f8f3">

But anyway, it doesn't work:
<img width="1048" alt="image" src="https://github.com/ShinyHobo/BG3-Modders-Multitool/assets/24209966/0f811007-25a8-4a93-8fde-fcb6ea7fcea2">
