### ISSUE TITLE
[Suggestion] Frames to/from Sheets Converter

### ISSUE THREAD

**Issue by andrew0030** [ShinyHobo/BG3-Modders-Multitool#151] opened 2023-08-29 00:25 UTC
So the idea is simple, a lot of UI elements (animated ones as an example) use sheets on which the images are placed.
Having a tool to do this job is very necessary, as once you get into things like Dice Making you quickly need to manage hundreds of files.

What the tool (frames -> sheets) should be able to do:

- [x] Take a folder as an input (maybe multi file selection instead?), and detect all the images (frames) in it.
- [x] Take a folder as an output target to save the sheets to
- [x] It should be able to roughly understand the order, this isn't necessarily to prevent user error, but rather to support as many use cases as possible. As an example blender outputs frames like: "0000, 0001, 0002" which should be equivalent to "0, 1, 02, 003"
- [x] It needs to take the height and width of frames into consideration. Maybe have an option to allow users to input the size.
- [x] It needs to have an option to specify how many rows and columns it should have.
- [x] users should either have the ability to specify a start and stop frame, or to specify a start and how many frames to render. Either one works.
- [x] Potentially have console info about images that exceed the specified size, or attempts to place more images on a sheet than what would mathematically be possible (20 frames on a 4 x 4 sheet)

What the tool (sheets -> frames) should be able to do:
- [x] Select file to convert and where to convert into
- [x] Options to specify how many rows/columns the sheet uses
- [x] Have a validation system to check if the image can be properly split into the given amount of columns and rows (no half pixels)
- [x] Suggestion but I would recommend to stick with the blender naming for frames so ("0001"... and so on)

**Comment by ShinyHobo** [comment] 2023-08-29 00:32
Duplicate of https://github.com/ShinyHobo/BG3-Modders-Multitool/issues/142 with more info and extra features (sheet to frames)

**Closed** 2023-09-11 20:57 UTC
Labels: enhancement
