### ISSUE TITLE
[CTD] [BUG] Crash on (Specific?) DDS mouseover

### ISSUE THREAD

**Issue by RandoRuda** [ShinyHobo/BG3-Modders-Multitool#324] opened 2024-01-30 00:35 UTC
> #### morrysillusion — Today at 11:19
> uhh hey just wondering is there any particular reason the multitool index would crash when mousing over a specific dds file lol? checked multiple times and its definitely happening specifically when mousing over this one. it was `textures\generated\public\shareddev\assets\houdini\cinematic\astarion_cazador\vfx_bc1_cinematic_astarion_back_carving_01.dds`

> #### Rando ⚠🌈🐸 — Today at 11:29
> Oh, I'm gonna test it out.

> #### morrysillusion — Today at 11:30
> i just scrolled over another one from that same folder and it crashed lol... however when i just search that path specifically it was fine and now loads alongside all my other search options. odd
or not the same folder, but still seems to be a similar file

> #### Rando ⚠🌈🐸 — Today at 11:31
> ~~[Deleted Swearing]~~ *Oh bother, I wasn't expecting this*. Same here.

> #### morrysillusion — Today at 11:31
> oh really?? really thought itd just be a me issue

**Comment by RandoRuda** [comment] 2024-01-30 00:43
### Further Info.

Did a little bit of testing. Appears to be related to anything in the `cinematic` sort of area. Some load, but slowly, others lead to a crash.

**Comment by ShinyHobo** [comment] 2024-01-30 20:32
Issue caused by accessviolationexception when converting dds to png for display. Fixed in 0.12.20e

**Comment by ShinyHobo** [comment] 2024-01-30 23:08
Also crashes on vfx_bc1_cinematic_astarion_back_carving_01. Fix did not take; randomly crashes still.

**Comment by ShinyHobo** [comment] 2024-01-31 00:06
Fixed in 0.12.20f

**Closed by ShinyHobo** 2024-01-31 00:06 UTC
Labels: bug
