### ISSUE TITLE
Clear GameObject cache when indexing

### ISSUE THREAD

**Issue by jgammey** [ShinyHobo/BG3-Modders-Multitool#137] opened 2023-08-26 23:50 UTC
After troubleshooting why the GameObject Explorer wasn't opening I found it was because all of the cache .json files had a single empty array. I think this happened because of a mistake or error when unpacking/decompressing/indexing. Deleting the cache files fixed my problem. I didn't see anything in the app that indicated this was the problem nor gave the option to clear the cache.

I suggest that when the "Index Files" function deletes the old database, it should also delete the cache.

**Comment by ShinyHobo** [comment] 2023-08-27 00:25
Those are separate tools and this is not intended behavior; your issue was caused by user error, most likely. Clicking the GameObject Explorer button without an index will result in an empty cache.

I will make changes to prevent cache files from being generated if no data is available, which would solve this problem.

**Comment by ShinyHobo** [comment] 2023-08-27 01:08
Changes have been made and will be in the next release.

**Closed by ShinyHobo** 2023-08-27 01:08 UTC
