### ISSUE TITLE
[Bug] Version GUI Does Not Update Meta.lsx

### ISSUE THREAD

**Issue by SoggyBurritoVR** [ShinyHobo/BG3-Modders-Multitool#333] opened 2024-03-02 23:39 UTC
Starting today, the main version control options no longer update the meta.lsx file/does not change the version.  

Below highlights the area I'm specifically talking about.

I tried clearing the appdata files/redownloading and using the current multitool core files.

![](https://i.imgur.com/jcy5s6f.png)

**Comment by SoggyBurritoVR** [comment] 2024-03-03 00:17
[meta.zip](https://github.com/ShinyHobo/BG3-Modders-Multitool/files/14471176/meta.zip)

**Comment by ShinyHobo** [comment] 2024-03-04 17:21
I cannot reproduce the issue; the file you uploaded doesn't seem to have any issues and setting it to read only didn't prevent me from updating it with the tool. I would try moving the directory or testing with a copy that isn't in your repo location.

**Comment by SoggyBurritoVR** [comment] 2024-03-05 05:45
Managed to replicate the bug with another user and possibly find the cause.  It has SOMETHING to do with the modfolder name.  

This mod has the bug, if you change the name of the 2 folder to `BaldursGay4` the issue goes away.  Had Rando test it, and they had the exact same results as I do.  

The issue is introduced when we add a dummy file `ForceOverrideLabel.txt` to trigger the override tag in mod manager.  

So to replicate, just pack the current mod.  To make it work, change the Folder names to `BaldursGay4` (that name works in my testing) there may be other names.  


[VoluptuousVistas.zip](https://github.com/ShinyHobo/BG3-Modders-Multitool/files/14490927/VoluptuousVistas.zip)

**Comment by SoggyBurritoVR** [comment] 2024-03-05 06:05
Small Update.  Found out if you simply add a number to the beggining of the folder names/lsx file necesary the issue goes away. 


Ex.  [9VoluptuousVistas.zip](https://github.com/ShinyHobo/BG3-Modders-Multitool/files/14491132/9VoluptuousVistas.zip)

**Comment by RandoRuda** [comment] 2024-03-05 06:13
Just wanting to confirm that I was able to reproduce the issue with the attached mod. It's a very curious issue.

[samplemod.zip](https://github.com/ShinyHobo/BG3-Modders-Multitool/files/14491188/samplemod.zip)

**Comment by ShinyHobo** [comment] 2024-03-05 14:14
Fixed in 0.12.26

**Closed by ShinyHobo** 2024-03-05 14:14 UTC
Labels: bug
